# Basic Jekyll config
title: My Website
description: A website about something cool
url: "https://johnsara04.github.io"

# Optional: choose a theme
theme: minima

# Tell GitHub this is a Jekyll site
plugins:
  - jekyll-relative-links

baseurl: "/mysite_static"
url: "https://johnsara04.github.io"
